Web/Models/ErrorViewModel.cs
namespace Web.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Web/Controllers/InvoiceController.cs
using Application.Implementation.Invoice.Commands;
using Application.Implementation.Invoice.Queries;
using Application.ViewModels;
using Domain.Entities.Invoices;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class InvoiceController:Controller
    {
        private readonly IMediator _mediator;
        protected IMediator Mediator => _mediator ?? HttpContext.RequestServices.GetService<IMediator>();
        public async Task<IActionResult> Index()
        {
            IEnumerable<Invoice> Invoices = await Mediator.Send(new GetAllInvoices());

            return View(Invoices);
        }
         
        public async Task<IActionResult> Delete(int num)
        {
            await Mediator.Send(new DeleteInvoice { Id=num});
            return RedirectToAction(nameof(Index));
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> Create(CreateInvoiceVM createInvoice)
        {
            await Mediator.Send(new CreateInvoice
            {
                InvoiceNum= createInvoice.InvoiceNum,   
                Customer= createInvoice.Customer,
                Date= createInvoice.Date,
                Description= createInvoice.Description,
                PaymentMethod= createInvoice.PaymentMethod,

            });
            return RedirectToAction(nameof(Index));
        }
         

    }
}

Web/Views/Invoice/Create.cshtml
@model Application.ViewModels.CreateInvoiceVM
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Create Inv";

}
<form class="form-group" method="post" asp-action="Create">
    <div class="form-control">
        <label asp-for="InvoiceNum">InvoiceNum</label>
        <input type="number" placeholder="Invoice Number" asp-for="InvoiceNum" />
    </div>
    <div class="form-control">
        <label asp-for="Date">InvoiceDate</label>
        <input type="date" placeholder="Invoice Date" asp-for="Date" />
    </div>
    <div class="form-control">
        <label asp-for="InvoiceNum">Customer</label>
        <input placeholder="Customer Name" asp-for="Customer" />
    </div>
    <div class="form-control">
        <label asp-for="PaymentMethod">PaymentMethod</label>
        <input placeholder="PaymentMethod" asp-for="PaymentMethod" />
    </div>
    <div class="form-control">
        <label asp-for="Description">Description</label>
        <textarea placeholder="Description" asp-for="Description">
        </textarea>

    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

Web/Views/Invoice/Index.cshtml
@model IEnumerable<Domain.Entities.Invoices.Invoice>
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    ViewData["Title"] = "Invoices";

}

<div>
    <div>
        <a class="btn btn-outline-info mb-1" asp-action="Create">Add New Invoice</a>
    </div>
    <table class="table table-bordered table-striped">
        <thead>
            <tr>
                <th>Invoice Number</th>
                <th>Date</th>
                <th>Customer</th>
                <th>Payment</th>
                <th>Description</th>
                <th>Delete</th>
             </tr>
        </thead>
        <tbody>
            @if (Model.Count() > 0)
            {
                foreach (var inv in Model)
                {
                    <tr>
                        <td>@inv.InvoiceNum</td>
                        <td>@inv.Date</td>
                        <td>@inv.Customer</td>
                        <td>@inv.PaymentMethod</td>
                        <td>@inv.Description</td>
                        <td><a asp-action="Delete" asp-route-num="@inv.InvoiceNum" class="btn btn-outline-danger" type="button">Delete</a></td>
                      
                    </tr>
                }
            }
        </tbody>
    </table>
</div>
 

Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Invoice" asp-action="Index">Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>